---
language: python
services: docker

env:
  global:
    - ROLE_NAME: kibana
  matrix:
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_PLAYBOOK: playbook-standalone.yml

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME geerlingguy.$ROLE_NAME
  - cd geerlingguy.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
---
services: docker

env:
  - distro: centos7
  - distro: centos6
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: ubuntu1204

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Test whether Kibana is running correctly.
  - 'docker exec --tty ${container_id} env TERM=xterm curl http://localhost:5601/'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
